TESTING: skip some tests that fail intermittently under Jenkins NO-MERGE-FORWARD
These tests often fail with:
org.apache.xmlrpc.XmlRpcException: Failed to read server's response: Connection refused
Possibly because test jobs run in parallel

This change should not be merged or cherry-picked to master