SCI-1733: IOperator's toString on empty functions causes StringIndexOutOfBoundsException test
This is the trace

java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.lang.AbstractStringBuilder.substring(AbstractStringBuilder.java:872)
	at java.lang.StringBuffer.substring(StringBuffer.java:412)
	at uk.ac.diamond.scisoft.analysis.fitting.functions.AOperator.toString(AOperator.java:134)
	at uk.ac.diamond.scisoft.analysis.fitting.functions.OperatorTest.testToString(OperatorTest.java:289)
--snip--